name: witnessed_art
description: A spiritual journey through AI-generated art.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  google_fonts: ^6.1.0
  google_mobile_ads: ^3.1.0
  purchases_flutter: ^6.0.0
  http: ^1.1.0
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
